### PR TITLE
chore: Adding rust build plugin

### PR DESCRIPTION
**Pull request by AlexsJones**
Adding rust support

### CODE REVIEW

**Comment by beeme1mr** [comment]
Can you include a Makefile entry for this and include it on the readme?
https://github.com/open-feature/schemas/blob/main/Makefile

**Review by toddbaert — APPROVED** [review]

**Comment by AlexsJones** [comment]
> Can you include a Makefile entry for this and include it on the readme? https://github.com/open-feature/schemas/blob/main/Makefile

Done, please check

**Review by toddbaert — APPROVED** [review]

**Comment by toddbaert** [comment]
> > Can you include a Makefile entry for this and include it on the readme? https://github.com/open-feature/schemas/blob/main/Makefile
> 
> Done, please check

Looks right to me!

**Comment by toddbaert** [comment]
@AlexsJones @beeme1mr 

I didn't catch it before merge, but the fact this was created as a `chore:` means that there was no release for it. I don't think this will be a problem for you though, @AlexsJones , since you're pulling this as a submodule, it's no relevant what's published to buf.

**Pull request merged**
